---
title: "Religiosity as Influenced by Intersectionality"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
load(here("data","data_constructed","analytical_data.RData"))
```


```{r}
#| Label: fig-Educational_attainment
#| fig-cap: Level of educational attainment among respondents. 
gss |>
  ggplot(aes(x=educ_attain, y=after_stat(prop), group=1))+
  geom_bar()+
  scale_y_continuous(labels=scales::percent)+
  labs(x="Education Level Attained", y=NULL, 
       title="Distribution of Education Level")+
  theme_bw()
```

```{r}
#| label: fig-Education_by_relig_affiliation
#| fig-cap: Level of educational attainment  of respondents by religious afiliation.
#gss |>
  #ggplot(aes(x=educ_attain, y=after_stat(prop), group=relig_affil, fill=relig_affil))+
  #geom_bar(position="dodge")+
  #scale_y_continuous(labels = scales::percent)+
  #labs(x=NULL, y=NULL, 
       #title="Education Level by Religious Affiliation")+
  #scale_fill_manual(values=qualpal(9)$hex)+
  #coord_flip()+
  #theme_bw()

gss |>  
  ggplot(aes(x=educ_attain, y=after_stat(prop), group=relig_affil, fill=relig_affil))+
  geom_bar(position="dodge")+
  #facet_wrap(~race)+
  #scale_fill_viridis_d()+
  scale_fill_manual(values=c("#154733","#FEE123","red", "blue", "black", "orange", "grey", "pink", "purple" ))+
  labs(x=NULL, y=NULL, 
       title="Education Level by Religious Affiliation")+
  coord_flip()+
  theme_bw()

```

```{r}
#| label: fig-Education_by_race
#| fig-cap: Level of educational attainment of respondents by racial identification.
#gss |>
 # ggplot(aes(x=educ_attain, y=after_stat(prop), group=1))+
  #geom_bar()+
  #facet_wrap(~race)+
  #scale_y_continuous(labels = scales::percent)+
  #labs(x=NULL, y=NULL, 
   #    title="Education Level by Racial Identification")+
  #coord_flip()+
  #theme_bw()

gss |>  
  ggplot(aes(x=educ_attain, y=after_stat(prop), group=race, fill=race))+
  geom_bar(position="dodge")+
  #facet_wrap(~race)+
  #scale_fill_viridis_d()+
  scale_fill_manual(values=c("#154733","#FEE123","red", "blue", "black" ))+
  labs(x=NULL, y=NULL, 
       title="Education Level by Racial Identification")+
  coord_flip()+
  theme_bw()

```

```{r}
#| label: fig-Education_by_sex
#| fig-cap: Level of educational attainment of respondents by sex.
gss |>
  ggplot(aes(x=educ_attain, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~resp_sex)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Education Level by Sex")+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Religious Attendance
#| fig-cap: Religious attendance of respondents. 
ggplot(data=subset(gss, !is.na(relig_attend)), aes(x=relig_attend, y=after_stat(prop), group=1))+
  geom_bar()+
  scale_y_continuous(labels=scales::percent)+
  labs(x="Religious Attendance", y=NULL, 
       title="Distribution of Religious Attendance")+
  theme_bw()
```

```{r}
#| label: fig-Religious Attendance by Sex
#| fig-cap: Religious attendance of respondents by sex.
gss |> filter(!is.na(relig_attend), !is.na(resp_sex)) |>
  ggplot(aes(x=relig_attend, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~resp_sex)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Religious Attendance by Sex")+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Religious_attendence_by_race
#| fig-cap: Religious attendence of respondents by racial identification.
gss |> filter(!is.na(relig_attend), !is.na(race)) |>
  ggplot(aes(x=relig_attend, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~race)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Education Level by Racial Identification")+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Religious_attend_by_resp_sex_and_relig_affil
#| fig-cap: Religious Attendence by Respondents Sex and Religious Affiliation
gss |>  
  ggplot(aes(x=relig_attend, y=after_stat(prop), group=resp_sex, fill=resp_sex))+
  geom_bar(position="dodge")+
  facet_wrap(~relig_affil)+
  #scale_fill_viridis_d()+
  scale_fill_manual(values=c("#154733","#FEE123"))+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Religious_attend_by_resp_sex_and_relig_affil
#| fig-cap: Religious Attendence by Respondents Sex and Religious Affiliation
gss |> filter(!is.na(relig_attend), !is.na(resp_sex),
              !is.na(relig_affil)) |>
  ggplot(aes(x=relig_affil, y=relig_attend, group=1))+
  geom_bar()+
  facet_wrap(~resp_sex)+
  #scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Religious Attendance by Sex and Race")+
  coord_flip()+
  theme_bw()
```

```{r}
#| Label: fig-Belief_in_god
#| fig-cap: Belief in god among respondents. 
ggplot(data=subset(gss, !is.na(believe_god)), aes(x=believe_god, y=after_stat(prop), group=1))+
  geom_bar()+
  scale_y_continuous(labels=scales::percent)+
  labs(x="Belief in God", y=NULL, 
       title="Distribution of Belief in God")+
  theme_bw()
```

```{r}
#| label: fig-Beleif_in_god_by_religious_affiliation
#| fig-cap: Belief in god of respondents by religious afiliation.
gss |> filter(!is.na(believe_god), !is.na(relig_affil)) |>
  ggplot(aes(x=believe_god, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~relig_affil)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Belief in god by Religious Affiliation")+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Belief_in_god_by_race
#| fig-cap: Belief in god of respondents by racial identification.
gss |> filter(!is.na(believe_god), !is.na(race)) |>
  ggplot(aes(x=believe_god, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~race)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Belief in god by Racial Identification")+
  coord_flip()+
  theme_bw()
```

```{r}
#| label: fig-Belief_in_god_by_sex
#| fig-cap: Belief in god of respondents by sex.
gss |> filter(!is.na(believe_god), !is.na(resp_sex)) |>
  ggplot(aes(x=believe_god, y=after_stat(prop), group=1))+
  geom_bar()+
  facet_wrap(~resp_sex)+
  scale_y_continuous(labels = scales::percent)+
  labs(x=NULL, y=NULL, 
       title="Belief in god by Sex")+
  coord_flip()+
  theme_bw()
```

```{r}
#| Label: fig-Religiousity_by_sex_and_race
#| fig-cap: religiousity by repsondents sex and race
gss |>
  group_by(race, resp_sex) |>
  summarize(religiosity=mean(religiosity)) |>
  ungroup() |>
  ggplot(aes(x=race, y=religiosity, fill=resp_sex))+
  geom_col(position="dodge")+
  #scale_fill_viridis_d()+
  scale_fill_manual(values=c("#154733","#FEE123"))+
  theme_bw()

```


```{r}
#| Label: Modeling Religiosity 
model1 <- glm(religiosity~resp_sex*race+educ_attain*race, data=gss)
model2 <- update(model1, .~.+resp_age+as.factor(year))
model3 <- update(model2, .~.+relig_affil)
model4 <- update(model3,.~.+relig_affil*resp_sex)

```

```{r}
#| Label: fig-Rendering Models
#| fig-cap: Models of religiosity with interaction terms.
#to print to screen replace texreg with screenreg
textreg(list(model1, model2, model3, model4),
        custom.coef.names = c("",),
       digits = 3,
       caption.above=TRUE, 
       include.rsquared=TRUE,
       include.adjrs=FALSE,
       include.nobs=TRUE,
       include.rmse=FALSE)
```


