---
title: "Religiosity as Influenced by Intersectionality"
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

## Reading in Raw Data

```{r}
#| label: read-data
gss <- read_fwf(here("data","data_raw","GSS.dat"), 
                col_positions = 
                  fwf_positions(start=c(1, 6, 11, 16, 26, 31, 35, 40, 45, 49, 54, 59, 64, 69, 74),
                                end  =c(5, 10, 15, 20, 30, 34, 39, 44, 48, 53, 58, 63, 68, 73, 78),
                                col_names=c("HISPANIC", "RACECEN1", "RACECEN2", "RACECEN3",
                                            "AGE", "EDUC", "SEX", "RACE", "RELIG", "ATTEND",
                                            "RELITEN", "PRAY", "GOD", "AFTERLIF", "YEAR")))


```

## Code variables

```{r}
#| label: code-vars
gss <- gss |>
  mutate(year=YEAR,
         educ=ifelse(EDUC<0, NA, EDUC),
         attend=ifelse(ATTEND<0, NA, ATTEND),
         sex=ifelse(SEX<0, NA, SEX),
         relig=ifelse(RELIG<0, NA, RELIG),
         pray=ifelse(PRAY<0, NA, PRAY),
         god=ifelse(GOD<0, NA, GOD),
         age=ifelse(AGE<0, NA, AGE),
         race=ifelse(RACE<0, NA, RACE),
         afterlife=ifelse(AFTERLIF<0, NA, AFTERLIF),
         racecen1=ifelse(RACECEN1<0, NA, RACECEN1),
         racecen2=ifelse(RACECEN2<0, NA, RACECEN2),
         racecen3=ifelse(RACECEN3<0, NA, RACECEN3),
         hispanic=ifelse(HISPANIC<0, NA, HISPANIC),
         reliten=ifelse(RELITEN<0, NA, RELITEN))
```

```{r}
#| label: check-ed missing values
#table(gss$EDUC, gss$educ, exclude=NULL)
#table(gss$SEX, gss$sex, exclude=NULL)
#table(gss$ATTEND, gss$attend, exclude=NULL)
#table(gss$RELIG, gss$relig, exclude=NULL)
#table(gss$PRAY, gss$pray, exclude=NULL)
#table(gss$GOD, gss$god, exclude=NULL)
#table(gss$AGE, gss$age, exclude=NULL)
```

```{r}
#| label: Collapsing racial identifications.
gss$racecat <- factor(ifelse(gss$racecen1==1, "white",
                             ifelse(gss$racecen1==2, "black",
                                    ifelse(gss$hispanic>=2 &
                                             gss$hispanic<=47,
                                           "hispanic",
                                           ifelse(gss$racecen1>=4 & gss$racecen1<=5 & gss$racecen1>=7 & gss$racecen1<=10, "asain",
                                                  ifelse(gss$racecen1==3 & gss$racecen1>=11 & gssracecen1<=14, "indigenous/pacific islander",
                                                         NA))))),
                      levels=c("white", "black", "hispanic", "asian", "indigenous/pacific islander"))

```

```{r}
#| label: collapsing highest educational attainment.
gss$edattain <- factor(ifelse(gss$educ<=11, "less than high school",
                              ifelse(gss$educ==12, "high school",
                                     ifelse(gss$educ>=13 & 
                                              gss$educ<=15,
                                            "some college",
                                            ifelse(gss$educ==16,
                                                   "bachelors",
                                                   ifelse(gss$educ>=17 & 
                                                            gss$educ<=20,
                                                          "graduate", NA))))),
                       levels=c("less than high school","high school",
                                "some college","bachelors", "graduate"))
```

```{r}
#| label: recoding religious preference variable
gss$religpref <- factor(ifelse(gss$relig==1, "protestant",
                               ifelse(gss$relig==2, "catholic",
                                      ifelse(gss$relig==3, "jewish",
                                             ifelse(gss$relig==4, "none",
                                                    ifelse(gss$relig==5, "other", NA))))),
                        levels=c("protestant", "catholic", "jewish", "none", "other"))



```

```{r}
#| label: collapsing religious attendance
gss$religattend <- factor(ifelse(gss$attend == 0, "never",
                                 ifelse(gss$attend>=1 & gss$attend<=2,
                                        "yearly",
                                        ifelse(gss$attend>=3 & gss$attend<=4,
                                               "monthly",
                                               ifelse(gss$attend>=5 &
                                                        gss$attend<=7,
                                                      "weekly",
                                                      ifelse(gss$attend==8,
                                                              "more than weeky", NA))))),
                          levels=c("never","yearly","monthly","weekly",
                                   "more than weeky"))
```

```{r}
#| label: Collapsing Prayer Frequency
gss$prayfreq <- factor(ifelse(gss$pray == 6, "never",
                                 ifelse(gss$pray>=4 & gss$pray<=5,
                                        "weekly",
                                        ifelse(gss$pray>=2 & gss$pray<=3,
                                               "daily",
                                               ifelse(gss$pray==1,
                                                      "more than daily", NA)))),
                          levels=c("never","weekly","daily",
                                   "more than daily"))
```

```{r}
#| label: collapsing belief in god
gss$bgod <- factor(ifelse(gss$god >=1 & gss$god<=2, "no belief",
                                 ifelse(gss$god==3, "higher power",
                                        ifelse(gss$god>=4 & gss$god<=5,
                                               "belief/doubt",
                                               ifelse(gss$god==6,
                                                      "no doubt", NA)))),
                          levels=c("no belief","higher power","belief/doubt",
                                   "no doubt"))
```

```{r}
#| label: renaming sex variable
gss$ssex <- factor(ifelse(gss$sex==1, "male",
                         ifelse(gss$sex==2, "female", NA)),
                  levels=c("male","female")) 
```

```{r}
#| label: renaming reliten variable
gss$ssex <- factor(ifelse(gss$reliten==1, "strong",
                         ifelse(gss$reliten==2, "not strong",
                                ifelse(gss$reliten==3, "somewhat strong",
                                iflse(gss$reliten==4, "no religion", NA)))),
                  levels=c("strong", "not strong", "somewhat strong", "no religion")) 
```

```{r}
#| label: reverse coding prayer frequency
gss$pray <- 7-gss$pray
```

```{r}
#| label: recoding reliten variable

```

```{r}
#| label: Standardizing belief in relgiosity variables.
standardize <- function(x) {
  (x-mean(x, na.rm=TRUE))/sd(x, na.rm=TRUE)
}
gss <- gss |>
  mutate(religiosity=standardize(standardize(attend)+
                                   standardize(pray)+standardize(god)+
                                   standardize(reliten)))
```

```{r}
#| label: verifying alpha
#alpha(gss[, c("attend", "pray", "god", "reliten")])
```

```{r}
#| label: coding age as cohorts
#gss$bcohort <- gss$year-gss$age
#cohort_breaks <- c(1880, seq(from=1900, to=2010, by=10))
#cohort_names <- paste(cohort_breaks[1:length(cohort_breaks)-1],
                      #cohort_breaks[2:length(cohort_breaks)]-1, sep="-")
#gss$bcohort10 <- cut(gss$bcohort, breaks=cohort_breaks, labels=cohort_names, 
                     #right=FALSE)
```

```{r}
#| label: creating religiosity through fa.
#gss$relfact <- fa(gss[, c("attend", "pray", "god")],
              #nfactors=1, rotate="oblimin")
```

```{r}
#| label: final variables check-ed
#table(gss$educ, gss$edattain, exclude=NULL)
#table(gss$attend, gss$religattend, exclude=NULL)
#table(gss$pray, gss$prayfreq, exclude=NULL)
#table(gss$god, gss$bgod, exclude=NULL)
#table(gss$sex, gss$ssex, exclude=NULL)
```

## Save it all

```{r}
#| label: save-analytical-data
gss <- gss |>
  select(year, edattain, ssex, religattend,
         prayfreq, racecat, religiosity, religpref, age)

save(gss, file=here("data","data_constructed","analytical_data.RData"))
```