---
title: "Religiosity by Education"
shorttitle: "Paper"
abstract: An Abstract
keywords: [keyword1, keyword2]
thanks: Thanks to everyone for checking this out.
reference-section-title: References
bibliography: ../bibliography/project.bib
csl: ../bibliography/chicago-parenthetical.csl
format:
  aog-article-pdf:
    keep-tex: false
    include-in-header: 
      text: |
        \usepackage{dcolumn}
#  submittable-pdf:
#     keep-tex: false
#     fig-pos: "!t"
#     include-in-header: 
#       text: |
#         \usepackage{dcolumn}
  submittable-docx: default
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

# Introduction

Religious importance for some individuals in the United States has changed over the last century. The U.S. census reports an increasing population of those who religion is not a central feature of their lives. This increasing population of non-religious individuals is occurring within a system historically rooted in religion. One of the founding principles of the United States is the right to practice any religion. Why then are more and more people opting to practice no religion in the end of the 20th and beginning of the 21st century? One factor associated with the decline of personal religious importance may be education leading to, on average, a result showing as education increases, religious importance decreases. This research paper will examine the association between level of education and religious importance from 1970 through 2020 to see how this association varies with time and across gender. 

In order to examine the association between the levels of education and importance of religion it is important to first consider a few variables. First, in order to measure how important religion is to a person, a term must be identified. This term is religiosity. It describes how important religion is to an individual. It is usually a compost measure of religious service attendance, prayer frequency, and intensity of belief in the afterlife. The specific criteria is detailed in the methods section. Identifying religiosity gives the ability to examine the relation between levels of education and religious importance. But, why include the time range of 1970-2020? Furthermore, why consider gender?

The United States experienced a large increase in education after 1950. With social programs such as the G.I. Bill and Pell Grants, each year more people have access to higher education. The percentage of the total population earning a degree past high school has increased. This gives a unique opportunity to examine the association between the levels of education and religiosity as the percentage of the educated population increases. We should expect to see a change in the level of religiosity. Including gender is important because the gender demographic has changed over this time also. In 1970, higher education institutions were primarily occupied by males. Today, females outnumber most males on these campuses. This demographic change will likely influence the association between education and religiosity as the composition of the group to be studied will be changing internally. This may provide further areas of research. If there is a difference in the association between education and religiosity between men and women, on average, it will be interesting to examine why and what possible factors lead to this potential finding.[@alba1990]  

# Background

# Data and Methods
The raw data set contains variables intended to measure educational trends, variables intended to construct the variable religiosity, and additional variables considering gender, race, and potential financial measures. The data set was collected from the GSS website on 11 May 2023, and the file size is 4.8 Mb. The survey is a national survey and therefore is generalizable to the U.S. population. The education variable measures trends in educational achievement by recording an individual's highest degree earned. Religiosity is often used to measure the quality of an individual's religious beliefs, experiences, and social significance. The five most commonly used variables used to measure religiosity are present here; religious importance, prayer frequency, religious attendance, belief in god, and belief in an afterlife. The additional variable of religious preference tracks a respondent's declared religious affiliation. The sex variable tracks a respondent's declared gender. 
The additional variables of race, income, wealth, and childhood religious affiliation are collected for potential consideration. Race records the respondent's declared race. Income and wealth measures a family's yearly income and collective wealth respectively, as declared by the respondent. The childhood religious affiliation tracks a respondent's declared childhood religious affiliation. 
Data was available for education, sex, race, religious preference, and religious attendance for all years from 1972 through 2022. Other variables were not available for each year and therefore will be addressed in building the analytic data set. 

# Results

# Conclusions
